#!/bin/sh

# Run go test
output=$(node --test) 
exit_code=$?

# Check if the test failed
if [ $exit_code -ne 0 ]; then
  echo "go test failed:"
  echo "$output"
  exit 1 # Return Error Code
fi

# Output succeeded
echo "$output"

exit 0